// <auto-generated />
namespace MovieProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class data_annotation_url : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(data_annotation_url));
        
        string IMigrationMetadata.Id
        {
            get { return "202005120717346_data_annotation_url"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
